# Task 1

In [2]:
import numpy as np
from scipy.spatial import cKDTree
import matplotlib.pyplot as plt
import random
from scipy import sparse

In [66]:
#initializing our birds positions
def initialize_birds(L, N):
    x_positons = np.random.uniform(0, L, N)
    y_positons = np.random.uniform(0, L, N) 

    combined = np.vstack((x_positons, y_positons)).T
    return combined

# we have to make a 2d vector of velocities
def initialize_velocities(positions, v_0):

    xes = positions[0:, 0:1]
    yes = positions[0:, 1:] * 1j
    z = xes + yes

    angles = np.angle(z)
    vx = v_0 * np.cos(angles)
    vy = v_0 * np.sin(angles)    

    combined = np.column_stack((vx, vy))
    return combined

# calculating angles of birds vs horiontal line
def calc_angles(positions):

    xes = positions[0:, 0:1]
    yes = positions[0:, 1:] * 1j
    z = xes + yes

    angles = np.angle(z)
    return angles

# add noise in radians
def add_noise(noise_val_degrees, number):
    noise = np.random.uniform(-noise_val_degrees, noise_val_degrees, number)
    noise_radians = np.radians(noise)

    return noise_radians

def find_nearest_neighbors(positons):
    pass


def new_direction(direction):
    pass


def new_velocity(velocity):
    pass

# Initialization parameters

L = 2
N = 10
r = 1
r_b = 4
v_0 = 2
a = 0.15

t_steps = 1

#  Here we initialize our birds postions and velocities
positions = initialize_birds(L, N)
velocities = initialize_velocities(positions, v_0)
angles = calc_angles(positions)

for t in range(t_steps):
    # Creation of birds tree 
    birds_tree = cKDTree(positions, boxsize=[L,L])
    dist = birds_tree.sparse_distance_matrix(birds_tree,max_distance=r,output_type='coo_matrix') # format wyniku (ptak i, ptak j, dystans)

    dist_copy = dist.copy()
    dist_copy_dense = dist_copy.todense()
    dist_no_zero = dist_copy_dense != 0
    dist_copy_dense[dist_no_zero] = 1

    exp_angles_vec = np.exp(1j * angles)
    sum_average_direction = np.dot(dist_copy_dense, exp_angles_vec)
    noise = add_noise(5, N).T
    new_angles = np.angle(sum_average_direction) + a * noise
        



# dist is a sparse matrix where distances beetween birds calculated, output format is (bird_i, bird_j, distance)

#orient = np.random.uniform(-np.pi, np.pi, size=N)
#data = np.exp(orient[dist.col]*1j)
#neigh = sparse.coo_matrix(data, (dist.row(), dist.col()), shape = dist.get_shape()) # macierz do ktorej od razu wstawiamy w miejsca niezerowe macierzy exponenty
# trzeba policzyc elementy niezerowe od ptakow -> uzyskamy info ile ptakow
# w miejsca niezerowe macierzy dist trzeba zrobic exp(ithetai) gdzie theta_i to jest kąt między vektorem prędkości ptaka a poziomem

#dist_no_zero = dist != 0
#non_zero_index = dist.nonzero()



#sum_distances = np.sum(dist, axis=0)
print(new_angles)

#print(velocities)

[[0.78733355 0.78467203 0.76353353 0.77917585 0.7715056  0.76385571
  0.77653537 0.77242514 0.76874485 0.78746277]
 [0.76862027 0.76595876 0.74482026 0.76046258 0.75279232 0.74514244
  0.75782209 0.75371187 0.75003158 0.76874949]
 [0.76862027 0.76595876 0.74482026 0.76046258 0.75279232 0.74514244
  0.75782209 0.75371187 0.75003158 0.76874949]
 [0.72309836 0.72043685 0.69929834 0.71494066 0.70727041 0.69962052
  0.71230018 0.70818996 0.70450966 0.72322758]
 [0.65117556 0.64851405 0.62737555 0.64301787 0.63534762 0.62769773
  0.64037738 0.63626716 0.63258687 0.65130479]
 [0.70281979 0.70015828 0.67901978 0.6946621  0.68699184 0.67934196
  0.69202161 0.68791139 0.6842311  0.70294902]
 [0.67160194 0.66894043 0.64780193 0.66344425 0.655774   0.64812411
  0.66080376 0.65669354 0.65301325 0.67173117]
 [0.85406328 0.85140177 0.83026326 0.84590558 0.83823533 0.83058545
  0.8432651  0.83915488 0.83547458 0.8541925 ]
 [0.7513517  0.74869019 0.72755169 0.74319401 0.73552375 0.72787387
  0.74055352

## Test with calculating angles
This will be needed to properly update velocities of birds

In [39]:
positions = initialize_birds(L, N)
#print(positions)
xes = positions[0:, 0:1]
yes = positions[0:, 1:] * 1j
z = xes + yes

angles = np.angle(z)
vx = v_0 * np.cos(angles)
vy = v_0 * np.sin(angles)

vel = np.column_stack((vx, vy)) # problem with velocity solved
#print(angles)

noise = np.random.uniform(-5, 5, 5)
noise

array([-0.65919472, -3.14478449, -3.98176712,  1.38069003,  2.52309327])

## Fun with sparse matrices

In [5]:
import numpy as np
from scipy.sparse import csr_matrix

# create a 2-D representation of the matrix
A = np.array([[1, 0, 0, 0, 0, 0], [0, 0, 2, 0, 0, 1],\
 [0, 0, 0, 2, 0, 0]])
print("Dense matrix representation: \n", A)

# convert to sparse matrix representation 
S = csr_matrix(A)
print("Sparse matrix: \n",S)

# convert back to 2-D representation of the matrix
B = S.todense()
print("Dense matrix: \n", B)

g = B > 0
print(g)    # Here i can input numbers in nonzero indices 
B[g] = 8
print(B)

# thats good news, we succesfuly inputed numbers to sparse matrix 

test = dist.todense()
dist_numb = test != 0
test[dist_numb] = 1
#print(test)
new = csr_matrix(test)
nonzero_indices = new.nonzero()

print(type(nonzero_indices))

Dense matrix representation: 
 [[1 0 0 0 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]
Sparse matrix: 
   (0, 0)	1
  (1, 2)	2
  (1, 5)	1
  (2, 3)	2
Dense matrix: 
 [[1 0 0 0 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]
[[ True False False False False False]
 [False False  True False False  True]
 [False False False  True False False]]
[[8 0 0 0 0 0]
 [0 0 8 0 0 8]
 [0 0 0 8 0 0]]
<class 'tuple'>


## Angles done correctly

In [33]:
exponential_angles = np.exp(1j * angles)
exponential_angles_real_part = np.real(exponential_angles)
exponential_angles_imag_part = np.imag(exponential_angles)
#print(exponential_angles)
#print(exponential_angles_real_part)
#print(exponential_angles_imag_part)

a = 0.3 + 1j * 0.2
b = 0.4 + 1j * 0.1

a_angle = np.angle(a, True)
b_angle = np.angle(b, True)

c = a + b
d = np.angle(c)
d_angle = np.angle(c, True)
print(a_angle)
print(b_angle)
print(d_angle)

33.69006752597979
14.036243467926479
23.198590513648192
