# Task 1

In [2]:
import numpy as np
from scipy.spatial import cKDTree
import matplotlib.pyplot as plt
import random
from scipy import sparse

In [37]:
#initializing our birds positions
def initialize_birds(L, N):
    x_positons = np.random.uniform(0, L, N)
    y_positons = np.random.uniform(0, L, N) 

    combined = np.vstack((x_positons, y_positons)).T
    return combined

# we have to make a 2d vector of velocities
def initialize_velocities(positions, v_0):

    xes = positions[0:, 0:1]
    yes = positions[0:, 1:] * 1j
    z = xes + yes

    angles = np.angle(z)
    vx = v_0 * np.cos(angles)
    vy = v_0 * np.sin(angles)    

    combined = np.column_stack((vx, vy))
    return combined

# calculating angles of birds vs horiontal line
def calc_angles(positions):

    xes = positions[0:, 0:1]
    yes = positions[0:, 1:] * 1j
    z = xes + yes

    angles = np.angle(z)
    return angles

def find_nearest_neighbors(positons):
    pass


def new_direction(direction):
    pass


def new_velocity(velocity):
    pass

# Initialization parameters

L = 2
N = 10
r = 1
r_b = 4
v_0 = 2
a = 0.15

t_steps = 100

#  Here we initialize our birds postions and velocities
positions = initialize_birds(L, N)
velocities = initialize_velocities(positions, v_0)
angles = calc_angles(positions)

# Creation of birds tree 
birds_tree = cKDTree(positions, boxsize=[L,L])
dist = birds_tree.sparse_distance_matrix(birds_tree,max_distance=r,output_type='coo_matrix') # format wyniku (ptak i, ptak j, dystans)

# dist is a sparse matrix where distances beetween birds calculated, output format is (bird_i, bird_j, distance)

#orient = np.random.uniform(-np.pi, np.pi, size=N)
#data = np.exp(orient[dist.col]*1j)
#neigh = sparse.coo_matrix(data, (dist.row(), dist.col()), shape = dist.get_shape()) # macierz do ktorej od razu wstawiamy w miejsca niezerowe macierzy exponenty
# trzeba policzyc elementy niezerowe od ptakow -> uzyskamy info ile ptakow
# w miejsca niezerowe macierzy dist trzeba zrobic exp(ithetai) gdzie theta_i to jest kąt między vektorem prędkości ptaka a poziomem

dist_no_zero = dist != 0
non_zero_index = dist.nonzero()



sum_distances = np.sum(dist, axis=0)

print(velocities)

[[1.88898402 0.65706877]
 [1.21648868 1.5874997 ]
 [0.79958825 1.83320992]
 [1.22250398 1.58287208]
 [1.15967797 1.62946218]
 [0.95290871 1.75839842]
 [0.52239922 1.93056962]
 [0.92888687 1.77120557]
 [1.83092687 0.80480234]
 [1.99977843 0.02976948]]


## Test with calculating angles
This will be needed to properly update velocities of birds

In [17]:
positions = initialize_birds(L, N)
#print(positions)
xes = positions[0:, 0:1]
yes = positions[0:, 1:] * 1j
z = xes + yes

angles = np.angle(z)
vx = v_0 * np.cos(angles)
vy = v_0 * np.sin(angles)

vel = np.column_stack((vx, vy)) # problem with velocity solved
print(angles)

[[1.40220359]
 [0.7112598 ]
 [0.20999438]
 [0.72381125]
 [1.19445393]
 [1.09534422]
 [0.98274565]
 [1.11911765]
 [0.53276596]
 [0.39384235]]


## Fun with sparse matrices

In [5]:
import numpy as np
from scipy.sparse import csr_matrix

# create a 2-D representation of the matrix
A = np.array([[1, 0, 0, 0, 0, 0], [0, 0, 2, 0, 0, 1],\
 [0, 0, 0, 2, 0, 0]])
print("Dense matrix representation: \n", A)

# convert to sparse matrix representation 
S = csr_matrix(A)
print("Sparse matrix: \n",S)

# convert back to 2-D representation of the matrix
B = S.todense()
print("Dense matrix: \n", B)

g = B > 0
print(g)    # Here i can input numbers in nonzero indices 
B[g] = 8
print(B)

# thats good news, we succesfuly inputed numbers to sparse matrix 

test = dist.todense()
dist_numb = test != 0
test[dist_numb] = 1
#print(test)
new = csr_matrix(test)
nonzero_indices = new.nonzero()

print(type(nonzero_indices))

Dense matrix representation: 
 [[1 0 0 0 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]
Sparse matrix: 
   (0, 0)	1
  (1, 2)	2
  (1, 5)	1
  (2, 3)	2
Dense matrix: 
 [[1 0 0 0 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]
[[ True False False False False False]
 [False False  True False False  True]
 [False False False  True False False]]
[[8 0 0 0 0 0]
 [0 0 8 0 0 8]
 [0 0 0 8 0 0]]
<class 'tuple'>


## Angles done correctly

In [33]:
exponential_angles = np.exp(1j * angles)
exponential_angles_real_part = np.real(exponential_angles)
exponential_angles_imag_part = np.imag(exponential_angles)
#print(exponential_angles)
#print(exponential_angles_real_part)
#print(exponential_angles_imag_part)

a = 0.3 + 1j * 0.2
b = 0.4 + 1j * 0.1

a_angle = np.angle(a, True)
b_angle = np.angle(b, True)

c = a + b
d = np.angle(c)
d_angle = np.angle(c, True)
print(a_angle)
print(b_angle)
print(d_angle)

33.69006752597979
14.036243467926479
23.198590513648192
